development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: user
  pool: 5 
  username: root
  password: maheshwari

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: user_test
  pool: 5 
  username: root
  password: maheshwari
